create table if not exists 
cassandra_blacklist ( pattern varchar(255), constraint pattern_key primary key (pattern) )
engine=InnoDB default charset=utf8;

create table if not exists
cassandra_redlist ( pattern varchar(255), constraint pattern_key primary key (pattern) )
engine=InnoDB default charset=utf8;

create table if not exists
staff_journal_entries 
( uuid char(22) not null,
  written_by char(22) not null,
  written_at datetime not null,
  entry text,
  constraint uuid_key primary key (uuid),
  constraint written_by_person foreign key (written_by) references people (uuid) on delete restrict on update cascade )
engine=InnoDB default charset=utf8;

create table if not exists
staff_journal_references
( entry char(22) not null,
  person char(22) not null,
  constraint pair_key primary key (entry, person),
  constraint staff_journal_entry foreign key (entry) references staff_journal_entries (uuid) on delete restrict on update cascade,
  constraint about_whom foreign key (person) references people (uuid) on delete restrict on update cascade )
engine=InnoDB default charset=utf8;

alter table items add column if not exists effect varchar(64);

alter table items add column if not exists attributes text;

alter table items add column if not exists special_texture text;

create table if not exists item_tags
( item int not null,
  tag varchar(64) not null,
  constraint distinct_tags primary key (item, tag),
  constraint item_tagged foreign key (item) references item_templates (id) on delete restrict on update cascade )
engine=InnoDB default charset=utf8;

insert ignore into item_templates (id, name, default_base_color, avatar, wear_slot, description)
values (6, 'Snowball', 'FFFFFF', 'snowball', 12, 'A ball of snow that makes a playful missile.');

replace into item_templates (id, name, avatar)
values
(7, 'Axe', 'axe'),
(8, 'Bare Tree 1', 'bareTree1'),
(9, 'Bare Tree 2', 'bareTree2'),
(10, 'Bare Tree 3', 'bareTree3'),
(11, 'Bare Tree 4', 'bareTree4'),
(12, 'Bare Tree 5', 'bareTree5'),
(13, 'Bare Tree 6', 'bareTree6'),
(14, 'Bare Tree 7', 'bareTree7'),
(15, 'Bare Tree 8', 'bareTree8'),
(16, 'Bare Tree 9', 'bareTree9'),
(17, 'Barricade A', 'barricadeA'),
(18, 'Barricade B', 'barricadeB'),
(19, 'Bench 1', 'bench1'),
(20, 'Bench 2', 'bench2'),
(21, 'Big Rock 1', 'bigRock1'),
(22, 'Big Rock 2', 'bigRock2'),
(23, 'Big Rock 3', 'bigRock3'),
(24, 'Big Twisted Tree', 'bigTwistedTree'),
(25, 'Bike Rack 1', 'bikeRack1'),
(26, 'Bike Rack 2', 'bikeRack2'),
(27, 'Billboard Blank', 'billboardBlank'),
(28, 'Blank Signpost', 'blankSignpost'),
(29, 'Blue Flower', 'blueFlower'),
(30, 'Bollard 1', 'bollard1'),
(31, 'Bollard 2', 'bollard2'),
(32, 'Bollard 3', 'bollard3'),
(33, 'Bollard 4', 'bollard4'),
(34, 'Bollard 5', 'bollard5'),
(35, 'Bollard 6', 'bollard6'),
(36, 'Bollard 7', 'bollard7'),
(37, 'Bollard 8', 'bollard8'),
(38, 'Bollard 9', 'bollard9'),
(39, 'Bollard Sign Blank', 'bollardSignBlank'),
(40, 'Branch 1', 'branch1'),
(41, 'Branch 2', 'branch2'),
(42, 'Branch 3', 'branch3'),
(43, 'Branch 4', 'branch4'),
(44, 'Broken Stone Arch', 'brokenStoneArch'),
(45, 'Broken Stone Column 1', 'brokenStoneColumn1'),
(46, 'Broken Stone Column 2', 'brokenStoneColumn2'),
(47, 'Brown Rock', 'brownRock'),
(48, 'Brown Mushroom 1', 'brownShroom1'),
(49, 'Brown Mushroom 2', 'brownShroom2'),
(50, 'Brown Mushroom 3', 'brownShroom3'),
(51, 'Brown Mushroom 4', 'brownShroom4'),
(52, 'Brown Mushroom 5', 'brownShroom5'),
(53, 'Burgundy Mushroom 1', 'burgundyShroom1'),
(54, 'Burgundy Mushroom 2', 'burgundyShroom2'),
(55, 'Bus Bench', 'busBench'),
(56, 'Bus Stop 1', 'busStop1'),
(57, 'Bus Stop 2', 'busStop2'),
(58, 'Buttercups 1', 'buttercups1'),
(59, 'Buttercups 2', 'buttercups2'),
(60, 'Campfire', 'campfire'),
(61, 'Community Sign Blank 2', 'communitySignBlank2'),
(62, 'Community Sign Blank', 'communitySignBlank'),
(63, 'Complex Road Sign Blank', 'complexRoadSignBlank'),
(64, 'Fallen Branch', 'fallenBranch'),
(65, 'Fall Tree 1', 'fallTree1'),
(66, 'Fall Tree 2', 'fallTree2'),
(67, 'Fancy Directional Sign Blank 1', 'fancyDirectionalSignBlank1'),
(68, 'Fancy Sign Blank 2', 'fancySignBlank2'),
(69, 'Fancy Sign Blank 1', 'fancySignBlank'),
(70, 'Foliage 1', 'foliage1'),
(71, 'Foliage 2', 'foliage2'),
(72, 'Foliage 3', 'foliage3'),
(73, 'Foliage 4', 'foliage4'),
(74, 'Grass 10', 'grass10'),
(75, 'Grass 11', 'grass11'),
(76, 'Grass 12', 'grass12'),
(77, 'Grass 13', 'grass13'),
(78, 'Grass 14', 'grass14'),
(79, 'Grass 15', 'grass15'),
(80, 'Grass 16', 'grass16'),
(81, 'Grass 17', 'grass17'),
(82, 'Grass 18', 'grass18'),
(83, 'Grass 1', 'grass1'),
(84, 'Grass 2', 'grass2'),
(85, 'Grass 3', 'grass3'),
(86, 'Grass 4', 'grass4'),
(87, 'Grass 5', 'grass5'),
(88, 'Grass 6', 'grass6'),
(89, 'Grass 7', 'grass7'),
(90, 'Grass 8', 'grass8'),
(91, 'Grass 9', 'grass9'),
(92, 'Grave 1', 'grave1'),
(93, 'Grave 2', 'grave2'),
(94, 'Grave 3', 'grave3'),
(95, 'Fire Hydrant 1', 'hydrant1'),
(96, 'Fire Hydrant 2', 'hydrant2'),
(97, 'Fire Hydrant 3', 'hydrant3'),
(98, 'Large Crystal', 'largeCrystal'),
(99, 'Large Rock 1', 'largeRock1'),
(100, 'Large Rock 2', 'largeRock2'),
(101, 'Large Rock 3', 'largeRock3'),
(102, 'Log 10', 'log10'),
(103, 'Log 11', 'log11'),
(104, 'Log 12', 'log12'),
(105, 'Log 1', 'log1'),
(106, 'Log 2', 'log2'),
(107, 'Log 3', 'log3'),
(108, 'Log 4', 'log4'),
(109, 'Log 5', 'log5'),
(110, 'Log 6', 'log6'),
(111, 'Log 7', 'log7'),
(112, 'Log 8', 'log8'),
(113, 'Log 9', 'log9'),
(114, 'Log Fence 1', 'logFence1'),
(115, 'Mailbox 1', 'mailbox1'),
(116, 'Mailbox 2', 'mailbox2'),
(117, 'Medium Bush', 'mediumBush'),
(118, 'Medium Crystal', 'mediumCrystal'),
(119, 'Mushroom Cluster', 'mushroomCluster'),
(120, 'Newspaper Bin 10', 'newspaperBin10'),
(121, 'Newspaper Bin 1', 'newspaperBin1'),
(122, 'Newspaper Bin 2', 'newspaperBin2'),
(123, 'Newspaper Bin 3', 'newspaperBin3'),
(124, 'Newspaper Bin 4', 'newspaperBin4'),
(125, 'Newspaper Bin 5', 'newspaperBin5'),
(126, 'Newspaper Bin 6', 'newspaperBin6'),
(127, 'Newspaper Bin 7', 'newspaperBin7'),
(128, 'Newspaper Bin 8', 'newspaperBin8'),
(129, 'Newspaper Bin 9', 'newspaperBin9'),
(130, 'Park Bench 1', 'parkBench1'),
(131, 'Park Sign Blank 1', 'parkSignBlank1'),
(132, 'Pine Tree 10', 'pineTree10'),
(133, 'Pine Tree 11', 'pineTree11'),
(134, 'Pine Tree 1', 'pineTree1'),
(135, 'Pine Tree 2', 'pineTree2'),
(136, 'Pine Tree 3', 'pineTree3'),
(137, 'Pine Tree 4', 'pineTree4'),
(138, 'Pine Tree 5', 'pineTree5'),
(139, 'Pine Tree 6', 'pineTree6'),
(140, 'Pine Tree 7', 'pineTree7'),
(141, 'Pine Tree 8', 'pineTree8'),
(142, 'Pine Tree 9', 'pineTree9'),
(143, 'Pink Flower', 'pinkFlower'),
(144, 'Pink Mushroom 1', 'pinkShroom1'),
(145, 'Pink Mushroom 2', 'pinkShroom2'),
(146, 'Purple Flower 1', 'purpleFlower1'),
(147, 'Purple Flower 2', 'purpleFlower2'),
(148, 'Pylon Sign Blank 1', 'pylonSignBlank1'),
(149, 'Real Estate Sign Blank 1', 'realEstateSignBlank1'),
(150, 'Red Flower 1', 'redFlower1'),
(151, 'Red Mushroom 1', 'redShroom1'),
(152, 'Red Mushroom 2', 'redShroom2'),
(153, 'Red Mushroom 3', 'redShroom3'),
(154, 'Red Mushroom 4', 'redShroom4'),
(155, 'Red Mushroom 5', 'redShroom5'),
(156, 'Red Mushroom 6', 'redShroom6'),
(157, 'Red Mushroom 7', 'redShroom7'),
(158, 'Red Mushroom Pair', 'redShroomPair'),
(159, 'River Rock 1', 'riverRock1'),
(160, 'Rock 10', 'rock10'),
(161, 'Rock 11', 'rock11'),
(162, 'Rock 12', 'rock12'),
(163, 'Rock 13', 'rock13'),
(164, 'Rock 14', 'rock14'),
(165, 'Rock 15', 'rock15'),
(166, 'Rock 16', 'rock16'),
(167, 'Rock 17', 'rock17'),
(168, 'Rock 18', 'rock18'),
(169, 'Rock 19', 'rock19'),
(170, 'Rock 1', 'rock1'),
(171, 'Rock 20', 'rock20'),
(172, 'Rock 21', 'rock21'),
(173, 'Rock 22', 'rock22'),
(174, 'Rock 23', 'rock23'),
(175, 'Rock 24', 'rock24'),
(176, 'Rock 2', 'rock2'),
(177, 'Rock 3', 'rock3'),
(178, 'Rock 4', 'rock4'),
(179, 'Rock 5', 'rock5'),
(180, 'Rock 6', 'rock6'),
(181, 'Rock 7', 'rock7'),
(182, 'Rock 8', 'rock8'),
(183, 'Rock 9', 'rock9'),
(184, 'Rope Bridge', 'ropeBridge'),
(185, 'Rustic Lamp Post', 'rusticLampPost'),
(186, 'Shop Sign Blank 1', 'shopSignBlank1'),
(187, 'Shop Sign Blank 2', 'shopSignBlank2'),
(188, 'Shop Sign Blank 3', 'shopSignBlank3'),
(189, 'Shop Sign Blank 4', 'shopSignBlank4'),
(190, 'Shop Sign Blank 5', 'shopSignBlank5'),
(191, 'Shop Sign Blank 6', 'shopSignBlank6'),
(192, 'Sidewalk Decor Flag 2', 'sidewalkDecorFlag2'),
(193, 'Sidewalk Sign Blank 1', 'sidewalkSignBlank1'),
(194, 'Sidewalk Sign Blank 2', 'sidewalkSignBlank2'),
(195, 'Sidewalk Sign Blank 3', 'sidewalkSignBlank3'),
(196, 'Sidewalk Sign Blank 4', 'sidewalkSignBlank4'),
(197, 'Sidewalk Sign Blank 5', 'sidewalkSignBlank5'),
(198, 'Sign Blank 1', 'signBlank1'),
(199, 'Sign Blank 2', 'signBlank2'),
(200, 'Sign Blank 3', 'signBlank3'),
(201, 'Sign Post Blank 1', 'signPostBlank1'),
(202, 'Small Bush', 'smallBush'),
(203, 'Small Cabin', 'smallCabin'),
(204, 'Small Crystal', 'smallCrystal'),
(205, 'Small Pine Tree', 'smallPineTree'),
(206, 'Split Rail Fence 1', 'splitRailFence1'),
(207, 'Split Rail Fence 2', 'splitRailFence2'),
(208, 'Stone Bench 1', 'stoneBench1'),
(209, 'Stone Column', 'stoneColumn'),
(210, 'Stone Path 1', 'stonePath1'),
(211, 'Stone Path 2', 'stonePath2'),
(212, 'Stump 1', 'stump1'),
(213, 'Stump 2', 'stump2'),
(214, 'Stump 3', 'stump3'),
(215, 'Stump 4', 'stump4'),
(216, 'Stump 5', 'stump5'),
(217, 'Stump 6', 'stump6'),
(218, 'Stump 7', 'stump7'),
(219, 'Stump 8', 'stump8'),
(220, 'Stump 9', 'stump9'),
(221, 'Stump With Axe', 'stumpWithAxe'),
(222, 'Thin Mushroom 1', 'thinShroom1'),
(223, 'Thin Mushroom 2', 'thinShroom2'),
(224, 'Thin Mushroom 3', 'thinShroom3'),
(225, 'Thin Mushroom 4', 'thinShroom4'),
(226, 'Thin Mushroom 5', 'thinShroom5'),
(227, 'Tiny Bush 1', 'tinyBush1'),
(228, 'Tiny Bush 2', 'tinyBush2'),
(229, 'Trashcan 10', 'trashcan10'),
(230, 'Trashcan 11', 'trashcan11'),
(231, 'Trashcan 1', 'trashcan1'),
(232, 'Trashcan 2', 'trashcan2'),
(233, 'Trashcan 3', 'trashcan3'),
(234, 'Trashcan 4', 'trashcan4'),
(235, 'Trashcan 5', 'trashcan5'),
(236, 'Trashcan 6', 'trashcan6'),
(237, 'Trashcan 7', 'trashcan7'),
(238, 'Trashcan 8', 'trashcan8'),
(239, 'Trashcan 9', 'trashcan9'),
(240, 'Tree 10', 'tree10'),
(241, 'Tree 11', 'tree11'),
(242, 'Tree 12', 'tree12'),
(243, 'Tree 1', 'tree1'),
(244, 'Tree 2', 'tree2'),
(245, 'Tree 3', 'tree3'),
(246, 'Tree 4', 'tree4'),
(247, 'Tree 5', 'tree5'),
(248, 'Tree 6', 'tree6'),
(249, 'Tree 7', 'tree7'),
(250, 'Tree 8', 'tree8'),
(251, 'Tree 9', 'tree9'),
(252, 'Twoolies', 'twoolies'),
(253, 'Utility Box 1', 'utilityBox1'),
(254, 'Utility Box 2', 'utilityBox2'),
(255, 'Utility Box 3', 'utilityBox3'),
(256, 'White Flower 1', 'whiteFlower1'),
(257, 'White Flower 2', 'whiteFlower2'),
(258, 'White Flower 3', 'whiteFlower3'),
(259, 'White Flower 4', 'whiteFlower4'),
(260, 'White Flower 5', 'whiteFlower5'),
(261, 'White Flower 6', 'whiteFlower6'),
(262, 'White Flower 7', 'whiteFlower7'),
(263, 'Wood Bench 1', 'woodBench1'),
(264, 'Wood Bench 2', 'woodBench2'),
(265, 'Yard Sign Blank', 'yardSignBlank'),
(266, 'Yellow Flower', 'yellowFlower'),
(267, 'Yellow Mushroom', 'yellowMushroom'),
(268, 'Yellow Mushroom 1', 'yellowShroom1'),
(269, 'Yellow Mushroom 2', 'yellowShroom2'),
(270, 'Drinking Glass', '12-oz-glass'), 
(271, '1 Door Lower Cabinet', '1DoorLowerCabinet'), 
(272, '1 Door Upper Cabinet', '1DoorUpperCabinet'), 
(273, '2 Door Lower Cabinet', '2DoorLowerCabinet'), 
(274, '2 Door Upper Cabinet', '2DoorUpperCabinet'), 
(275, '2 Glass Door Cabinet', '2GlassDoorCabinet'), 
(276, '3-Drawer Cabinet', '3DrawerCabinet'), 
(277, 'Accordian-Fold Doors', 'accordionFoldDoors'), 
(278, 'Air Mattress', 'air-mattress'), 
(279, 'Allen Organ', 'allenorgan'), 
(280, 'Duck Box', 'ammoBox'), 
(281, 'angolo160W', 'angolo160W'), 
(282, 'angolo198W', 'angolo198W'), 
(283, 'angolo80W', 'angolo80W'), 
(284, 'angolo', 'angolo'), 
(285, 'Antelope Canyon Frame', 'AntelopeCanyonFrame'), 
(286, 'Parabolic Antenna', 'antenaParabolica'), 
(287, 'Laptop Computer 1', 'apple-ibook-2001'), 
(288, 'Desktop Computer 1', 'apple-imac-1998'), 
(289, 'Music Player', 'appleIpod'), 
(290, 'Desktop Computer 2', 'apple_pc'), 
(291, 'Apples', 'apples'), 
(292, 'Arch', 'arch'), 
(293, 'Armchair 3', 'armchair3'), 
(294, 'Armoire', 'armoire'), 
(295, 'Nut Dish', 'ashtray'), 
(296, 'aspirateur', 'aspirateur'), 
(297, 'assietteVerresCouverts', 'assietteVerresCouverts'), 
(298, 'AtorArriere', 'AtorArriere'), 
(299, 'AtorHaut', 'AtorHaut'), 
(300, 'autocuiseur', 'autocuiseur'), 
(301, 'Awning Bracket', 'awning_bracket'), 
(302, 'Baby High Chair', 'baby_high_chair'), 
(303, 'bacADouchePlat', 'bacADouchePlat'), 
(304, 'baguettePain', 'baguettePain'), 
(305, 'balancelle', 'balancelle'), 
(306, 'bandeja', 'bandeja'), 
(307, 'barbecue', 'barbecue'), 
(308, 'Bar Chair', 'bar_chair'), 
(309, 'Bar Stool', 'bar-stool'), 
(310, 'Bar Table', 'bar_table'), 
(311, 'Basic Camera', 'basic_camera'), 
(312, 'basketball net and board', 'basketball_net_and_board'), 
(313, 'bath L', 'bath_L'), 
(314, 'bathmat', 'bathmat'), 
(315, 'bathroom1', 'bathroom1'), 
(316, 'bathroom3', 'bathroom3'), 
(317, 'bathroom4', 'bathroom4'), 
(318, 'bathroom cupboard mirror', 'bathroom_cupboard_mirror'), 
(319, 'bathroom fan', 'bathroom_fan'), 
(320, 'bathroomFurniture', 'bathroomFurniture'), 
(321, 'bathroom sink', 'bathroom_sink'), 
(322, 'bathroom-tissue', 'bathroom-tissue'), 
(323, 'bathroom vanity', 'bathroom_vanity'), 
(324, 'bathtub jet system', 'bathtub_jet_system'), 
(325, 'Batterie', 'batterie'), 
(326, 'bd', 'bd'), 
(327, 'bdOuverte', 'bdOuverte'), 
(328, 'Beach Chair', 'beach_chair'), 
(329, 'Beige Sofa with 2 seats', 'beige_sofa_2seats'), 
(330, 'Beige Sofa', 'beige_sofa'), 
(331, 'Bench', 'bench'), 
(332, 'bibliotheque', 'bibliotheque'), 
(333, 'bibliothequeDroite', 'bibliothequeDroite'), 
(334, 'Bidet', 'bidet'), 
(335, 'Big Corner Desk', 'bigCornerDesk'), 
(336, 'Bike', 'bike'), 
(337, 'Birthday Cake', 'birthday_cake'), 
(338, 'Black Deck Chair', 'blackDeckChair'), 
(339, 'black Deck Table', 'blackDeckTable'), 
(340, 'Black Table', 'black_table'), 
(341, 'blackTupelo', 'blackTupelo'), 
(342, 'Blocks', 'blocks'), 
(343, 'bocalPoisson', 'bocalPoisson'), 
(344, 'boiteDeMouchoirs', 'boiteDeMouchoirs'), 
(345, 'boiteMetal', 'boiteMetal'), 
(346, 'bolDeRiz', 'bolDeRiz'), 
(347, 'Bonsai Tree', 'bonsai-tree'), 
(348, 'borderfence-main', 'borderfence-main'), 
(349, 'borderfence-small', 'borderfence-small'), 
(350, 'bordure', 'bordure'), 
(351, 'boucheVMC', 'boucheVMC'), 
(352, 'bougeoir', 'bougeoir'), 
(353, 'bouteille', 'bouteille'), 
(354, 'Bowl', 'bowl'), 
(355, 'box room', 'box_room'), 
(356, 'Boy Lying', 'boyLying'), 
(357, 'Boy Sitting', 'boySitting'), 
(358, 'Boy Standing', 'boyStanding'), 
(359, 'bread-plate', 'bread-plate'), 
(360, 'Broom', 'broom'), 
(361, 'Bucket', 'bucket'), 
(362, 'Bullet Trashcan', 'bullet-trash-can'), 
(363, 'Bureau 2', 'bureau2'), 
(364, 'Bureau 3', 'bureau3'), 
(365, 'Bureau', 'bureau'), 
(366, 'bureauEcolier', 'bureauEcolier'), 
(367, 'bureauInfoClair', 'bureauInfoClair'), 
(368, 'bureauInfoOuvert', 'bureauInfoOuvert'), 
(369, 'bureauInformatique', 'bureauInformatique'), 
(370, 'Burlap Sofa', 'burlap_sofa'), 
(371, 'Butterfly Frame', 'ButterflyFrame'), 
(372, 'Cabinet 2', 'cabinet2'), 
(373, 'Cabinet', 'cabinet'), 
(374, 'Cabinet With Basin', 'cabinetWithBasin'), 
(375, 'Café Chair', 'cafe-chair'), 
(376, 'Café Table', 'cafe-table'), 
(377, 'caffe final', 'caffe_final'), 
(378, 'cageFuret', 'cageFuret'), 
(379, 'calla lily with roses', 'calla_lily_with_roses'), 
(380, 'candleOrnament', 'candleOrnament'), 
(381, 'capa Scene', 'capa_Scene'), 
(382, 'captainsBed', 'captainsBed'), 
(383, 'carafeEau', 'carafeEau'), 
(384, 'carafeVin', 'carafeVin'), 
(385, 'cardboard-box', 'cardboard-box'), 
(386, 'cardGame', 'cardGame'), 
(387, 'carpet', 'carpet'), 
(388, 'casierBouteilles', 'casierBouteilles'), 
(389, 'Cooking Pot', 'casserole'), 
(390, 'cassetti cucina 45x60 Scene', 'cassetti_cucina_45x60_Scene'), 
(391, 'cassettiera', 'cassettiera'), 
(392, 'cassettieraW', 'cassettieraW'), 
(393, 'Cat', 'cat'), 
(394, 'CD Rack', 'CDrack'), 
(395, 'ceiling-lamp', 'ceiling-lamp'), 
(396, 'ceiling lamp globo feria', 'ceiling_lamp_globo_feria'), 
(397, 'ceramicHob', 'ceramicHob'), 
(398, 'Chair 3', 'chair3'), 
(399, 'Chair 4', 'chair4'), 
(400, 'Grandmother Chair', 'chair_granmother'), 
(401, 'Office Chair 6', 'chair_office_x'), 
(402, 'Office Chair 7', 'chair_office_y'), 
(403, 'chair-ottoman', 'chair-ottoman'), 
(404, 'chaise', 'chaise'), 
(405, 'chaiseCuisine', 'chaiseCuisine'), 
(406, 'chaiseJaune', 'chaiseJaune'), 
(407, 'chaiseOrange', 'chaiseOrange'), 
(408, 'chandelier-lamp', 'chandelier-lamp'), 
(409, 'changing-table', 'changing-table'), 
(410, 'cheminee', 'cheminee'), 
(411, 'Chessboard', 'chessboard'), 
(412, 'Chest Freezer', 'chest-freezer'), 
(413, 'Child''s Bed', 'children_bed'), 
(414, 'Child''s Swing', 'child_swing'), 
(415, 'Christmas Tree', 'christmas_tree'), 
(416, 'Classic Lamppost', 'classic-lamppost'), 
(417, 'clavier', 'clavier'), 
(418, 'clear sofa', 'clear_sofa'), 
(419, 'clicClac', 'clicClac'), 
(420, 'clicClacOuvert', 'clicClacOuvert'), 
(421, 'Clothes Basket', 'clothes-basket'), 
(422, 'Clothes Hanger', 'clothes-hanger'), 
(423, 'Clothes Horse', 'clothes-horse'), 
(424, 'Clothes Line', 'clothes_line'), 
(425, 'Clothes Washing Machine', 'clothes_washing_machine'), 
(426, 'cloture', 'cloture'), 
(427, 'Coffee Machine', 'coffee_machine'), 
(428, 'Coffee Maker', 'coffee-maker'), 
(429, 'Coffee Mug', 'coffee-mug'), 
(430, 'Coffee Table 2', 'coffee-table2'), 
(431, 'Coffee Table 1', 'coffee_table'), 
(432, 'Colored Fountain Frame', 'ColoredFountainFrame'), 
(433, 'column balustrade', 'column_balustrade'), 
(434, 'column balustrade corner', 'column_balustrade_corner'), 
(435, 'com bath2 cepillo', 'com_bath2_cepillo'), 
(436, 'com bath2 esponja', 'com_bath2_esponja'), 
(437, 'com bath2 jabon pijo', 'com_bath2_jabon_pijo'), 
(438, 'com bath2 peineta', 'com_bath2_peineta'), 
(439, 'com_bath2 soap', 'com_bath2_soap'), 
(440, 'com bath3', 'com_bath3'), 
(441, 'com bath3 toalla', 'com_bath3_toalla'), 
(442, 'com bath', 'com_bath'), 
(443, 'comoCiliegio', 'comoCiliegio'), 
(444, 'como', 'como'), 
(445, 'comodinoArancio', 'comodinoArancio'), 
(446, 'comodinoAzzurro', 'comodinoAzzurro'), 
(447, 'comodinoSinistroCiliegio', 'comodinoSinistroCiliegio'), 
(448, 'comodinoSinistro', 'comodinoSinistro'), 
(449, 'complements2', 'complements2'), 
(450, 'Concept Sedan 01v1', 'concept-sedan-01v1'), 
(451, 'Concept Sedan 01v2', 'concept-sedan-01v2'), 
(452, 'Concept Sedan 02', 'concept-sedan-02'), 
(453, 'Concept Sedan 02 sport', 'concept-sedan-02-sport'), 
(454, 'Concrete Bench', 'concrete-bench'), 
(455, 'Concrete Sidewalk', 'concrete-sidewalk'), 
(456, 'container', 'container'), 
(457, 'contemp living room', 'contemp_living_room'), 
(458, 'cookingPlate', 'cookingPlate'), 
(459, 'corner bathtub', 'corner_bathtub'), 
(460, 'cornerCabinet', 'cornerCabinet'), 
(461, 'cornerChina', 'cornerChina'), 
(462, 'corner', 'corner'), 
(463, 'couch', 'couch'), 
(464, 'couchPoofyPillows', 'couchPoofyPillows'), 
(465, 'couchTwoSeats', 'couchTwoSeats'), 
(466, 'counter', 'counter'), 
(467, 'couteauADecouper', 'couteauADecouper'), 
(468, 'couteauAPain', 'couteauAPain'), 
(469, 'craftsmanDoorClosed', 'craftsmanDoorClosed'), 
(470, 'creamer', 'creamer'), 
(471, 'credenza', 'credenza'), 
(472, 'cucina', 'cucina'), 
(473, 'cup', 'cup'), 
(474, 'curtain', 'curtain'), 
(475, 'curva', 'curva'), 
(476, 'curvaEsterna30', 'curvaEsterna30'), 
(477, 'curvaInterna30', 'curvaInterna30'), 
(478, 'custom-desk', 'custom-desk'), 
(479, 'dart game', 'dart_game'), 
(480, 'daybed', 'daybed'), 
(481, 'Toilet-paper', 'derouleurWC'), 
(482, 'desk2', 'desk2'), 
(483, 'desk lamp1', 'desk_lamp1'), 
(484, 'deskLamp1', 'deskLamp1'), 
(485, 'desk lamp2', 'desk_lamp2'), 
(486, 'deskLight', 'deskLight'), 
(487, 'desk table', 'desk_table'), 
(488, 'desserte', 'desserte'), 
(489, 'DianaWindow', 'DianaWindow'), 
(490, 'dining-chair', 'dining-chair'), 
(491, 'dining room', 'dining_room'), 
(492, 'dinner-plate', 'dinner-plate'), 
(493, 'displayCabinet', 'displayCabinet'), 
(494, 'diving-board', 'diving-board'), 
(495, 'doccia', 'doccia'), 
(496, 'dog', 'dog'), 
(497, 'Dog House 2', 'dog-house'), 
(498, 'Dog House 1', 'dogHouse'), 
(499, 'Doll', 'doll'), 
(500, 'Doll House', 'doll-house'), 
(501, 'Door 1', 'door1'), 
(502, 'Door Glass Panels', 'doorGlassPanels'), 
(503, 'Door Window Thick', 'door_window_thick'), 
(504, 'Door Window Thick Double 2×4', 'door_window_thick_double_2x4'), 
(505, 'Door Window Thick Double', 'door_window_thick_double'), 
(506, 'doppio', 'doppio'), 
(507, 'Double Door 2', 'double_door_2'), 
(508, 'Double Door', 'double_door'), 
(509, 'Double Door with Little Part', 'double_door_with_little_part'), 
(510, 'Double Oven', 'doubleOven'), 
(511, 'Double Vanity', 'double_vanity'), 
(512, 'Drawers', 'drawers'), 
(513, 'Dresser 1', 'dressoir'), 
(514, 'Black Dresser', 'dressoirNoir'), 
(515, 'Dryer Machine', 'dryer_machine'), 
(516, 'DVD', 'dvd'), 
(517, '16×9 Screen', 'ecran16_9'), 
(518, 'Eiffel Tower Frame', 'EiffelTowerFrame'), 
(519, 'Electric Outlet 2', 'electricOutlet2'), 
(520, 'Electric Outlet', 'electricOutlet'), 
(521, 'Electric Water Heater Big', 'electric_water_heater_big'), 
(522, 'Electric Water Heater Small', 'electric_water_heater'), 
(523, 'elementHautSalon', 'elementHautSalon'), 
(524, 'Elevator Door', 'elevator-door'), 
(525, 'Elevator', 'elevator'), 
(526, 'emergencyGlassDoubleDoor', 'emergencyGlassDoubleDoor'), 
(527, 'enceinteColonne', 'enceinteColonne'), 
(528, 'eponge', 'eponge'), 
(529, 'escalierColimacon2', 'escalierColimacon2'), 
(530, 'escalierColimacon', 'escalierColimacon'), 
(531, 'escritorio', 'escritorio'), 
(532, 'estintore', 'estintore'), 
(533, 'etabli', 'etabli'), 
(534, 'etagereEnfant', 'etagereEnfant'), 
(535, 'etageres', 'etageres'), 
(536, 'etau', 'etau'), 
(537, 'EtretatFrame', 'EtretatFrame'), 
(538, 'ext chair', 'ext_chair'), 
(539, 'Exterior Door 1', 'exterior-door-01'), 
(540, 'Exterior Door 2', 'exterior-door-02'), 
(541, 'Exterior Door 3', 'exterior-door-03'), 
(542, 'Exterior Door 5', 'exterior-door-05'), 
(543, 'Exterior Door 7', 'exterior-door-07'), 
(544, 'External Unity Air Conditioning', 'external-unity-air-conditioning'), 
(545, 'ext table', 'ext_table'), 
(546, 'fancyFrontDoor', 'fancyFrontDoor'), 
(547, 'fancyWindow', 'fancyWindow'), 
(548, 'fanPalm', 'fanPalm'), 
(549, 'farola1', 'farola1'), 
(550, 'fauteuil', 'fauteuil'), 
(551, 'fauteuilNoir', 'fauteuilNoir'), 
(552, 'female-01-casual-clothing', 'female-01-casual-clothing'), 
(553, 'female01', 'female01'), 
(554, 'female02', 'female02'), 
(555, 'female03', 'female03'), 
(556, 'fence grid', 'fence_grid'), 
(557, 'fence grid gate', 'fence_grid_gate'), 
(558, 'fence picket', 'fence_picket'), 
(559, 'fencepost1', 'fencepost1'), 
(560, 'fencepost2', 'fencepost2'), 
(561, 'Clothes Iron', 'fer'), 
(562, 'Ficus', 'ficus'), 
(563, 'Filing Cabinet', 'filing-cabinet'), 
(564, 'Fire Hydrant 4', 'fire-hydrant'), 
(565, 'Fireplace 1', 'fireplace1'), 
(566, 'Fireplace 2', 'fireplace2'), 
(567, 'fivePanesWindow', 'fivePanesWindow'), 
(568, 'fixed window 2×2', 'fixed_window_2x2'), 
(569, 'flashlight', 'flashlight'), 
(570, 'flipper', 'flipper'), 
(571, 'fluorescent', 'fluorescent'), 
(572, 'fluorescent-strip', 'fluorescent-strip'), 
(573, 'folded clothes', 'folded_clothes'), 
(574, 'folding-table', 'folding-table'), 
(575, 'frame1', 'frame1'), 
(576, 'frame2', 'frame2'), 
(577, 'Norway Photos', 'frame3HorizontalNorwayPhotos'), 
(578, 'Summer Photos', 'frame3VerticalSummerPhotos'), 
(579, 'Vertical Frame', 'frame_vertical'), 
(580, 'frigo', 'frigo'), 
(581, 'frigorifero Scene', 'frigorifero_Scene'), 
(582, 'Full Bookcase', 'full-bookcase'), 
(583, 'furnace', 'furnace'), 
(584, 'fut', 'fut'), 
(585, 'futon-couch', 'futon-couch'), 
(586, 'Garage Door 2', 'garageDoor2'), 
(587, 'Garage Door 1', 'garage-door'), 
(588, 'Garden Faucet', 'garden-faucet'), 
(589, 'Garden Umbrella', 'gardenUmbrella'), 
(590, 'gasHob', 'gasHob'), 
(591, 'gate grind', 'gate_grind'), 
(592, 'Iron Gate', 'gate_iron'), 
(593, 'gaz', 'gaz'), 
(594, 'Gas Water Heater', 'gaz_water_heater'), 
(595, 'gelDouche', 'gelDouche'), 
(596, 'Girl Sitting Ground', 'girlSittingGround'), 
(597, 'Girl Sitting Table', 'girlSittingTable'), 
(598, 'Girl Standing', 'girlStanding'), 
(599, 'Glass Dining Table', 'glass-dining-table'), 
(600, 'Glass Door Kitchen Cabinet', 'glassDoorKitchenCabinet'), 
(601, 'Glass Doors Opened', 'glassDoorsOpened'), 
(602, 'Glasses', 'glasses'), 
(603, 'Glass Office Table', 'glass_table_office'), 
(604, 'grandStaircaseDark', 'grandStaircaseDark'), 
(605, 'grandStaircase', 'grandStaircase'), 
(606, 'Toaster', 'grillePain'), 
(607, 'grillNgauge', 'grillNgauge'), 
(608, 'guacal', 'guacal'), 
(609, 'HaiVanPassFrame', 'HaiVanPassFrame'), 
(610, 'hallTable', 'hallTable'), 
(611, 'Hamburger', 'hamburger'), 
(612, 'Hanging Clothes 1', 'hanging-clothes1'), 
(613, 'Hanging Clothes 2', 'hanging-clothes2'), 
(614, 'Hanging Restaurant Light', 'hanging-restaurant-light'), 
(615, 'Headphones', 'headphones'), 
(616, 'highball-glass', 'highball-glass'), 
(617, 'highBoyDresser', 'highBoyDresser'), 
(618, 'holding Female 1', 'holdingFemale01'), 
(619, 'holding Female 2', 'holdingFemale02'), 
(620, 'holding Female 3', 'holdingFemale03'), 
(621, 'holding Male 1', 'holdingMale01'), 
(622, 'Horseshoe Bend Frame', 'HorseShoeBendFrame'), 
(623, 'Hose Reel', 'hose-reel'), 
(624, 'Hospital Bed', 'hospital-bed'), 
(625, 'Fax-Printer-Copier', 'imprimanteFaxPhotocopieur'), 
(626, 'Inari Frame', 'InariFrame'), 
(627, 'Indoor Bike', 'indoor-bike'), 
(628, 'Induction Cooker 2 Zones', 'induction-cooker-2-zones'), 
(629, 'Induction Cooker 4 Zones', 'induction-cooker-4-zones'), 
(630, 'Inkjet Printer and Scanner', 'inkjet_and_scanner_printer'), 
(631, 'Intercom', 'intercom'), 
(632, 'Intercom with Screen', 'intercom_with_screen'), 
(633, 'internal-unity-air-conditioning', 'internal-unity-air-conditioning'), 
(634, 'interrupteur', 'interrupteur'), 
(635, 'Invoice', 'invoice'), 
(636, 'Iron Bed', 'iron_bed'), 
(637, 'Iron Railing 4', 'iron-railing-02'), 
(638, 'Iron Railing 1', 'iron-railing-1'), 
(639, 'Iron Railing 2', 'iron-railing-2'), 
(640, 'Iron Railing 3', 'iron-railing-3'), 
(641, 'isola cucina 150×90 Scene', 'isola_cucina_150x90_Scene'), 
(642, 'Spa Bath', 'jacuzzi'), 
(643, 'Japanese Style Screen', 'japanese_style_screen'), 
(644, 'jar', 'jar'), 
(645, 'Kids'' Desk Chair', 'kids_desk_chair'), 
(646, 'Kids'' Desk Table', 'kids_desk_table'), 
(647, 'Kids'' Shelves', 'kids_shelves'), 
(648, 'Kids'' Wooden Desk', 'Kids_wooden_desk'), 
(649, 'kitchenSink', 'kitchenSink'), 
(650, 'kitchenSinkWithMarble', 'kitchenSinkWithMarble'), 
(651, 'Kitchen Stool', 'kitchen_stool'), 
(652, 'kitchen tool1', 'kitchen_tool1'), 
(653, 'kitchen tool2', 'kitchen_tool2'), 
(654, 'kitchen tool3', 'kitchen_tool3'), 
(655, 'kitchen tool4', 'kitchen_tool4'), 
(656, 'kitchenTools', 'kitchenTools'), 
(657, 'kleed grieks', 'kleed_grieks'), 
(658, 'Simple Ladder', 'ladder_simple'), 
(659, 'Water Ladder', 'ladder_water'), 
(660, 'Lamp 2', 'lamp2'), 
(661, 'Halogen Lamp', 'lampeHalogene'), 
(662, 'Office Lamp', 'lamp_office'), 
(663, 'Large Couch', 'largeCouch'), 
(664, 'Lattice Chair', 'latticeChair'), 
(665, 'lavastoviglie', 'lavastoviglie'), 
(666, 'lavello doppio Scene', 'lavello_doppio_Scene'), 
(667, 'lavello', 'lavello'), 
(668, 'Leather Sofa', 'leather_sofa'), 
(669, 'Letters Box', 'letters_box'), 
(670, 'Letters', 'letters'), 
(671, 'lettoArancio', 'lettoArancio'), 
(672, 'lettoAzzurro', 'lettoAzzurro'), 
(673, 'lettoCiliegio', 'lettoCiliegio'), 
(674, 'letto', 'letto'), 
(675, 'lettoSoppalcoArancio', 'lettoSoppalcoArancio'), 
(676, 'lettoSoppalcoAzzurro', 'lettoSoppalcoAzzurro'), 
(677, 'lightSwitch', 'lightSwitch'), 
(678, 'litBebe', 'litBebe'), 
(679, 'lit', 'lit'), 
(680, 'littlebank', 'littlebank'), 
(681, 'Little Lamp 1', 'little_lamp1'), 
(682, 'Little Lamp 2', 'little_lamp2'), 
(683, 'Little Lamp 3', 'little_lamp3'), 
(684, 'Living Lamp', 'living_lamp'), 
(685, 'Living Room Lamp 1', 'livingroom_lamp1'), 
(686, 'Living Room Table', 'living_room_table'), 
(687, 'livreAvecReliure', 'livreAvecReliure'), 
(688, 'lombardyPoplar', 'lombardyPoplar'), 
(689, 'lustreBoule', 'lustreBoule'), 
(690, 'lyingDownFemale01', 'lyingDownFemale01'), 
(691, 'lyingDownMale01', 'lyingDownMale01'), 
(692, 'lyingDownMale02', 'lyingDownMale02'), 
(693, 'maceta', 'maceta'), 
(694, 'male01', 'male01'), 
(695, 'male-01-suit', 'male-01-suit'), 
(696, 'male02', 'male02'), 
(697, 'male03', 'male03'), 
(698, 'marteau', 'marteau'), 
(699, 'medicoscopia bottle2', 'medicoscopia_bottle2'), 
(700, 'medicoscopia bottle', 'medicoscopia_bottle'), 
(701, 'medicoscopia box', 'medicoscopia_box'), 
(702, 'Medium Indoor Plant', 'mediumIndoorPlant'), 
(703, 'mensolaAcero', 'mensolaAcero'), 
(704, 'mensolaArancio', 'mensolaArancio'), 
(705, 'mensolaAzzurra', 'mensolaAzzurra'), 
(706, 'mensolaBlu', 'mensolaBlu'), 
(707, 'mensolaCiliegio', 'mensolaCiliegio'), 
(708, 'mensolaCurvaAcero', 'mensolaCurvaAcero'), 
(709, 'mensolaCurvaArancio', 'mensolaCurvaArancio'), 
(710, 'mensolaCurvaAzzurro', 'mensolaCurvaAzzurro'), 
(711, 'mensolaCurvaBlu', 'mensolaCurvaBlu'), 
(712, 'mensolaCurvaMarrone', 'mensolaCurvaMarrone'), 
(713, 'mensolaMarrone', 'mensolaMarrone'), 
(714, 'mensola', 'mensola'), 
(715, 'metal glass table', 'metal_glass_table'), 
(716, 'meubleChaussures', 'meubleChaussures'), 
(717, 'meubleChevet', 'meubleChevet'), 
(718, 'meubleHiFiHaut', 'meubleHiFiHaut'), 
(719, 'meubleMicroOnde', 'meubleMicroOnde'), 
(720, 'meubleMural', 'meubleMural'), 
(721, 'meublePC', 'meublePC'), 
(722, 'meubleSalleDeBain', 'meubleSalleDeBain'), 
(723, 'microOnde', 'microOnde'), 
(724, 'mid-century-bench-sofa', 'mid-century-bench-sofa'), 
(725, 'mid-century-chair', 'mid-century-chair'), 
(726, 'mid-century-sofa', 'mid-century-sofa'), 
(727, 'MIDI-keyboard', 'MIDI-keyboard'), 
(728, 'mini stereo', 'mini_stereo'), 
(729, 'mirror', 'mirror'), 
(730, 'mobile45160W', 'mobile45160W'), 
(731, 'mobile45198W', 'mobile45198W'), 
(732, 'mobile4580W', 'mobile4580W'), 
(733, 'mobile90160W', 'mobile90160W'), 
(734, 'mobile90198W', 'mobile90198W'), 
(735, 'mobile9080W', 'mobile9080W'), 
(736, 'mobileangoloCiliegio', 'mobileangoloCiliegio'), 
(737, 'mobileAngoloInternoArancio', 'mobileAngoloInternoArancio'), 
(738, 'mobileAngoloInterno', 'mobileAngoloInterno'), 
(739, 'mobileAngolo', 'mobileAngolo'), 
(740, 'mobileArancio', 'mobileArancio'), 
(741, 'mobileAzzurro', 'mobileAzzurro'), 
(742, 'mobileCiliegio', 'mobileCiliegio'), 
(743, 'mobile cucina Scene', 'mobile_cucina_Scene'), 
(744, 'mobilettoBlu', 'mobilettoBlu'), 
(745, 'mobilettoGrande', 'mobilettoGrande'), 
(746, 'mobilettoLavaboBlu', 'mobilettoLavaboBlu'), 
(747, 'mobilettoLavaboWenge', 'mobilettoLavaboWenge'), 
(748, 'mobilettoPiccolo', 'mobilettoPiccolo'), 
(749, 'mobilettoSpecchioBlu', 'mobilettoSpecchioBlu'), 
(750, 'mobilettoSpecchioWenge', 'mobilettoSpecchioWenge'), 
(751, 'mobilettowenge', 'mobilettowenge'), 
(752, 'mocassin', 'mocassin'), 
(753, 'Modern Armchair', 'modern_armchair'), 
(754, 'LCD Monitor', 'monitorLCD'), 
(755, 'Mont Blanc Frame', 'MontBlancFrame'), 
(756, 'Mower', 'mower'), 
(757, 'Music Player base for Tablet', 'mp3_base_for_ipad'), 
(758, 'Mug', 'mug'), 
(759, 'Neon Light', 'neon'), 
(760, 'Newspaper', 'newspaper'), 
(761, 'newWindowDk', 'newWindowDk'), 
(762, 'Niagara Falls Frame', 'NiagaraFallsFrame'), 
(763, 'office box', 'office_box'), 
(764, 'Office Chair 2', 'officeChair2'), 
(765, 'Office Chair 3', 'officeChair3'), 
(766, 'Office Chair 4', 'office-chair'), 
(767, 'Office Chair 1', 'office_chair'), 
(768, 'Office Chair 5', 'officeChair'), 
(769, 'office furniture1', 'office_furniture1'), 
(770, 'oil-servers', 'oil-servers'), 
(771, 'old jar', 'old_jar'), 
(772, 'open-cardboard-box', 'open-cardboard-box'), 
(773, 'oriental-rug', 'oriental-rug'), 
(774, 'outdoor staircase', 'outdoor_staircase'), 
(775, 'ovalMirror', 'ovalMirror'), 
(776, 'ovenFront', 'ovenFront'), 
(777, 'oven Scene', 'oven_Scene'), 
(778, 'p40', 'p40'), 
(779, 'painted-bench', 'painted-bench'), 
(780, 'palm', 'palm'), 
(781, 'pancaFratinoSing', 'pancaFratinoSing'), 
(782, 'pantry', 'pantry'), 
(783, 'pareDouche', 'pareDouche'), 
(784, 'parfumAmbiance', 'parfumAmbiance'), 
(785, 'park-light', 'park-light'), 
(786, 'park-trashcan', 'park-trashcan'), 
(787, 'parque', 'parque'), 
(788, 'patioDoorOpened', 'patioDoorOpened'), 
(789, 'patioDoor', 'patioDoor'), 
(790, 'patioDoorSideWindow', 'patioDoorSideWindow'), 
(791, 'patioGlassDoor', 'patioGlassDoor'), 
(792, 'patioGlassDoorUnit', 'patioGlassDoorUnit'), 
(793, 'patioSideDoor', 'patioSideDoor'), 
(794, 'pavesDeVerre', 'pavesDeVerre'), 
(795, 'pcstul', 'pcstul'), 
(796, 'pedestal-vase-lamp', 'pedestal-vase-lamp'), 
(797, 'penbox', 'penbox'), 
(798, 'pencil1', 'pencil1'), 
(799, 'pencil2', 'pencil2'), 
(800, 'pensileAcero', 'pensileAcero'), 
(801, 'pensileAngolo', 'pensileAngolo'), 
(802, 'pensileArancio', 'pensileArancio'), 
(803, 'pensileAzzurro', 'pensileAzzurro'), 
(804, 'pensileBlu', 'pensileBlu'), 
(805, 'pensile cucina 45x90 Scene', 'pensile_cucina_45x90_Scene'), 
(806, 'pensile cucina Scene', 'pensile_cucina_Scene'), 
(807, 'pensileCurva', 'pensileCurva'), 
(808, 'pensileDoppio', 'pensileDoppio'), 
(809, 'pensileMarrone', 'pensileMarrone'), 
(810, 'pensileVetro', 'pensileVetro'), 
(811, 'percolateur', 'percolateur'), 
(812, 'pesePersonne', 'pesePersonne'), 
(813, 'petiteCommode', 'petiteCommode'), 
(814, 'petiteTableSalon', 'petiteTableSalon'), 
(815, 'petitReveil', 'petitReveil'), 
(816, 'peugeot-308', 'peugeot-308'), 
(817, 'Phone', 'phone'), 
(818, 'pianoDroit', 'pianoDroit'), 
(819, 'pianoIsola', 'pianoIsola'), 
(820, 'Picnic Table', 'picnic_table'), 
(821, 'Picture', 'picture'), 
(822, 'pictureWindow', 'pictureWindow'), 
(823, 'pileMagazines', 'pileMagazines'), 
(824, 'pile', 'pile'), 
(825, 'pinewoodRackFullHeightHalfWidth', 'pinewoodRackFullHeightHalfWidth'), 
(826, 'pinewoodRackFullHeight', 'pinewoodRackFullHeight'), 
(827, 'pinewoodRackLowHeight', 'pinewoodRackLowHeight'), 
(828, 'pinewoodRackMediumHeight', 'pinewoodRackMediumHeight'), 
(829, 'Pizza', 'pizza'), 
(830, 'plancheADecouper', 'plancheADecouper'), 
(831, 'plancheARepasser', 'plancheARepasser'), 
(832, 'plastic chair', 'plastic_chair'), 
(833, 'plastic storage box', 'plastic_storage_box'), 
(834, 'plate-and-ustensils', 'plate-and-ustensils'), 
(835, 'poele', 'poele'), 
(836, 'polygonalRoof', 'polygonalRoof'), 
(837, 'pompeBiere', 'pompeBiere'), 
(838, 'porch-column-01', 'porch-column-01'), 
(839, 'porch-column-02', 'porch-column-02'), 
(840, 'porch-column-03', 'porch-column-03'), 
(841, 'porch-light', 'porch-light'), 
(842, 'portable', 'portable'), 
(843, 'portail', 'portail'), 
(844, 'portemanteaux2', 'portemanteaux2'), 
(845, 'portemanteaux', 'portemanteaux'), 
(846, 'portillon', 'portillon'), 
(847, 'potBrossesADent', 'potBrossesADent'), 
(848, 'Potted Plant 2', 'potplant2'), 
(849, 'Pottery', 'pottery'), 
(850, 'poubelleInox', 'poubelleInox'), 
(851, 'prise', 'prise'), 
(852, 'priseTelephonique', 'priseTelephonique'), 
(853, 'privacyFence2', 'privacyFence2'), 
(854, 'propane-stove', 'propane-stove'), 
(855, 'puerta', 'puerta'), 
(856, 'Wooden Door', 'wooden_door'), 
(857, 'puff', 'puff'), 
(858, 'Punching Ball', 'punching-ball'), 
(859, 'putekasse', 'putekasse'), 
(860, 'quakingAspen', 'quakingAspen'), 
(861, 'Rabbit', 'rabbit'), 
(862, 'raccordo80W', 'raccordo80W'), 
(863, 'radiateur', 'radiateur'), 
(864, 'radiateurVertical', 'radiateurVertical'), 
(865, 'radiator 7section', 'radiator_7section'), 
(866, 'railing glass', 'railing_glass'), 
(867, 'rainGutterPart1', 'rainGutterPart1'), 
(868, 'rampeArcCercle', 'rampeArcCercle'), 
(869, 'rampe', 'rampe'), 
(870, 'rasoir', 'rasoir'), 
(871, 'rectangle-swimming-pool', 'rectangle-swimming-pool'), 
(872, 'rectangularFivePanesWindow', 'rectangularFivePanesWindow'), 
(873, 'rectangularMirror', 'rectangularMirror'), 
(874, 'recycling-bin', 'recycling-bin'), 
(875, 'red-wine-bottle-01', 'red-wine-bottle-01'), 
(876, 'reflex camera', 'reflex_camera'), 
(877, 'refridgerator', 'refridgerator'), 
(878, 'renault-scenic', 'renault-scenic'), 
(879, 'residential-trashcan', 'residential-trashcan'), 
(880, 'rideau', 'rideau'), 
(881, 'Roasted Chicken', 'roasted-chicken'), 
(882, 'Robinet Faucet', 'robinet'), 
(883, 'Rocking Chair', 'rocking_chair'), 
(884, 'Round Carpet', 'round-carpet'), 
(885, 'Rounded Edges Railing 2', 'roundedEdgesRailing2'), 
(886, 'Rounded Edges Railing 1', 'roundedEdgesRailing'), 
(887, 'Round Swimming Pool', 'round-swimming-pool'), 
(888, 'Round Table 2', 'roundTable2'), 
(889, 'Ruffled Vase', 'ruffledVase'), 
(890, 'salontafel', 'salontafel'), 
(891, 'Saloon Lamp', 'saloon_lamp'), 
(892, 'Saloon Table', 'saloon_table'), 
(893, 'Sandpit', 'sandpit'), 
(894, 'sassafras', 'sassafras'), 
(895, 'sauna 120x120', 'sauna_120x120'), 
(896, 'savon', 'savon'), 
(897, 'scaletta', 'scaletta'), 
(898, 'scie', 'scie'), 
(899, 'scooter', 'scooter'), 
(900, 'screen-door', 'screen-door'), 
(901, 'scrivania160W', 'scrivania160W'), 
(902, 'seat leon', 'seat_leon'), 
(903, 'secheCheveux', 'secheCheveux'), 
(904, 'secretarysDesk', 'secretarysDesk'), 
(905, 'sedia', 'sedia'), 
(906, 'Sewing Machine', 'sewing_machine'), 
(907, 'sgabello', 'sgabello'), 
(908, 'sh3dMag', 'sh3dMag'), 
(909, 'Shampoo', 'shampoo'), 
(910, 'Steel Storage Shelves', 'shelves_storage_steel'), 
(911, 'Wood Storage Shelves 2', 'shelves_storage_wood2'), 
(912, 'Wood Storage Shelves', 'shelves_storage_wood'), 
(913, 'Shelving', 'shelving'), 
(914, 'Shopping Basket', 'shopping-basket'), 
(915, 'Shovel', 'shovel'), 
(916, 'Shower Curtain', 'showerCurtain'), 
(917, 'Showerhead and Faucet', 'showerHeadAndFaucet'), 
(918, 'silla teca', 'silla_teca'), 
(919, 'Simple Shutter', 'simpleShutter'), 
(920, 'simple Sofa', 'simple_sofa'), 
(921, 'singolo', 'singolo'), 
(922, 'Female Sitting 1', 'sitFemale01'), 
(923, 'Female Sitting 2', 'sitFemale02'), 
(924, 'Female Sitting 3', 'sitFemale03'), 
(925, 'Male Sitting 1', 'sitMale01'), 
(926, 'Male Sitting 2', 'sitMale02'), 
(927, 'Male Sitting 3', 'sitMale03'), 
(928, 'Six Panel French Doors', 'sixDoorFrenchStyle'), 
(929, 'Slider Pocket Door', 'sliderPocketDoor'), 
(930, 'Small Bookshelves', 'smallbookshelves'), 
(931, 'Smaller Railing', 'smallerRailing'), 
(932, 'Small Glass', 'smallGlass'), 
(933, 'Small lavatory', 'small_lavatory'), 
(934, 'Small Wrought Iron Rails', 'smallWroughtIronRails'), 
(935, 'Smiley', 'smiley'), 
(936, 'Sneakers', 'sneakers'), 
(937, 'Sofa 1', 'sofa1'), 
(938, 'Sofa 3 Single', 'sofa3Single'), 
(939, 'Sofa 4', 'sofa4'), 
(940, 'Sofa White Beige', 'sofa_white_beige'), 
(941, 'Solar Panel 140W', 'solar_panel_140W'), 
(942, 'souris', 'souris'), 
(943, 'sphere', 'sphere'), 
(944, 'Spoon', 'spoon'), 
(945, 'Spray Bottle', 'spray-bottle'), 
(946, 'squeezer', 'squeezer'), 
(947, 'Squirrel Frame', 'SquirrelFrame'), 
(948, 'Stainless Steel Shelf', 'stainlessSteelShelf'), 
(949, 'Staircase 180° Landing', 'staircase_180_landing'), 
(950, 'Staircase 180° Long', 'staircase_180_long'), 
(951, 'Staircase 360° Circle', 'staircase_360_circle'), 
(952, 'Staircase 90° Bottom', 'staircase_90_bottom'), 
(953, 'Staircase 90° High Open', 'staircase_90_high_open'), 
(954, 'Staircase 90° Landing', 'staircase_90_landing'), 
(955, 'Staircase 90° Top', 'staircase_90_top'), 
(956, 'Staircase Handrail Horizontal', 'staircase_handrail_hor'), 
(957, 'Staircase Ladder Steep', 'staircase_ladder_steep'), 
(958, 'Staircase Samba 265x150x85', 'staircase_samba_265x150x85'), 
(959, 'Stair Ladder Loft', 'stair_ladder_loft'), 
(960, 'Stairs 180° Circular No Top Step Rail',
              'stairs_180_circular_notopstep_rail'), 
(961, 'Stairs 180° Square', 'stairs_180_square'), 
(962, 'Stairs 90° Closed Legal High', 'stairs_90_closed_legal_high'), 
(963, 'Stairs Legal', 'stairs_legal'), 
(964, 'Stairs Rail', 'stairs_rail'), 
(965, 'Stairs Top Curve 90°', 'stairs_topcurve_90'), 
(966, 'Stair Straight Open Stringer', 'stair_straight_open_stringer'), 
(967, 'Stapler', 'stapler'), 
(968, 'Statue of Liberty Frame', 'StatueOfLibertyFrame'), 
(969, 'Metal Stepladder', 'step-ladder-metal'), 
(970, 'Wood Stepladder', 'step-ladder-wood'), 
(971, 'Stereo Amplifier', 'stereo_amplifier'), 
(972, 'Stroller', 'stroller'), 
(973, 'stylo', 'stylo'), 
(974, 'Sugar', 'sugar'), 
(975, 'Suits Racked', 'suits_racked'), 
(976, 'Sushi Tray', 'sushi_tray'), 
(977, 'Sweet Home 3D Kompakt', 'SweetHome3DKompakt'), 
(978, 'Swimming Pool 2', 'swimming-pool'), 
(979, 'Swimming Pool 1', 'swimmingPool'), 
(980, 'Table 2', 'table2'), 
(981, 'Table 3', 'table3'), 
(982, 'Table 4', 'table4'), 
(983, 'tableauElectrique', 'tableauElectrique'), 
(984, 'tableauMulet', 'tableauMulet'), 
(985, 'tableauVisage3', 'tableauVisage3'), 
(986, 'tableauVisage', 'tableauVisage'), 
(987, 'tableauYing', 'tableauYing'), 
(988, 'tableBasse2', 'tableBasse2'), 
(989, 'tableBasse', 'tableBasse'), 
(990, 'tableCuisine2', 'tableCuisine2'), 
(991, 'tableCuisine', 'tableCuisine'), 
(992, 'tableGnome', 'tableGnome'), 
(993, 'Grandmother''s Marble Table', 'table_granmother_marble'), 
(994, 'Table Lamp', 'table_lamp'), 
(995, 'Tablet', 'tablet'), 
(996, 'Wood and Iron Table', 'table_wood_and_iron'), 
(997, 'tabouretBar', 'tabouretBar'), 
(998, 'tabouretPiano', 'tabouretPiano'), 
(999, 'tabouret', 'tabouret'), 
(1000, 'Tape Measure', 'tape-measure'), 
(1001, 'tavolino', 'tavolino'), 
(1002, 'tavoloFratino', 'tavoloFratino'), 
(1003, 'tavolo', 'tavolo'), 
(1004, 'Teapot', 'teapot'), 
(1005, 'Teddy Bear', 'teddyBear'), 
(1006, 'Throw Pillow', 'throwPillow'), 
(1007, 'Tiger Frame', 'TigerFrame'), 
(1008, 'toast', 'toast'), 
(1009, 'toilet_hang_round', 'toilet_hang_round'), 
(1010, 'toilets_unit_jay_hardy', 'toilets_unit_jay_hardy'), 
(1011, 'toitureArdoiseBleue', 'toitureArdoiseBleue'), 
(1012, 'toitureArdoiseRouge', 'toitureArdoiseRouge'), 
(1013, 'TorontoOntarioPlaceFrame', 'TorontoOntarioPlaceFrame'), 
(1014, 'tournevis', 'tournevis'), 
(1015, 'tourPC', 'tourPC'), 
(1016, 'towelMedicineCabinet', 'towelMedicineCabinet'), 
(1017, 'Towel Rack 1', 'towel-rack'), 
(1018, 'Towel Rack 2', 'towel_rack'), 
(1019, 'Toy Train', 'toyTrain'), 
(1020, 'Track Lights', 'track-lights'), 
(1021, 'Traditional Shutter', 'traditionalShutter'), 
(1022, 'Train', 'train'), 
(1023, 'Trampoline', 'trampoline'), 
(1024, 'transat', 'transat'), 
(1025, 'Tray', 'tray'), 
(1026, 'Tricycle', 'tricycle'), 
(1027, 'tringleRideau', 'tringleRideau'), 
(1028, 'Truck', 'truck'), 
(1029, 'Trundle Bed', 'trundleBed'), 
(1030, 'Large Trunk', 'trunk-large'), 
(1031, 'Tubular Chair', 'tubular_chair'), 
(1032, 'Toucan Frame', 'TucanFrame'), 
(1033, 'turn-window', 'turn-window'), 
(1034, 'TV Center', 'TVCenter'), 
(1035, 'TV', 'tv'), 
(1036, 'twoPartsShutter', 'twoPartsShutter'), 
(1037, 'upperCabinet2', 'upperCabinet2'), 
(1038, 'upperCabinet', 'upperCabinet'), 
(1039, 'utensilsPot', 'utensilsPot'), 
(1040, 'Utility Shelving', 'utility-shelving'), 
(1041, 'Vase 1', 'vase1'), 
(1042, 'Vase 2', 'vase2'), 
(1043, 'Vase 3', 'vase3'), 
(1044, 'Vase 5', 'vase5'), 
(1045, 'VaticanMuseumFrame', 'VaticanMuseumFrame'), 
(1046, 'VeniceFrame', 'VeniceFrame'), 
(1047, 'vent_round', 'vent_round'), 
(1048, 'Water Glass', 'verreEau'), 
(1049, 'Flute Glass', 'verreFlute'), 
(1050, 'Tall Drink Glass', 'verreLongDrink'), 
(1051, 'Wine Glass', 'verreVin'), 
(1052, 'Video Projector', 'video-projector'), 
(1053, 'vitrineNoire', 'vitrineNoire'), 
(1054, 'vitrine', 'vitrine'), 
(1055, 'Compact Car', 'VW-new-beetle'), 
(1056, 'Wall-mounted Flat TV', 'wall-flat-tv'), 
(1057, 'wall-hanger', 'wall-hanger'), 
(1058, 'Wall Lamp Artwork', 'wall-lamp-artwork'), 
(1059, 'Wall Spotlight', 'wall-spotlight'), 
(1060, 'wardrobe1', 'wardrobe1'), 
(1061, 'Washer Dryer', 'washer_dryer'), 
(1062, 'Water Cooler', 'water_cooler'), 
(1063, 'Water Fountain', 'waterFountain'), 
(1064, 'Water Lily Frame', 'WaterLilyFrame'), 
(1065, 'Water', 'water'), 
(1066, 'Weeping Willow', 'weepingWillow'), 
(1067, 'Wheelie Bin', 'wheelie_bin'), 
(1068, 'white_kitchen_chair', 'white_kitchen_chair'), 
(1069, 'white_kitchen_table', 'white_kitchen_table'), 
(1070, 'whitePatioDoorOpened', 'whitePatioDoorOpened'), 
(1071, 'window-01', 'window-01'), 
(1072, 'window-08-02', 'window-08-02'), 
(1073, 'window-08', 'window-08'), 
(1074, 'window 2×1 medium with large pane',
               'window_2x1_medium_with_large_pane'), 
(1075, 'window 2×1 with sliders', 'window_2x1_with_sliders'), 
(1076, 'window 2×3 arched', 'window_2x3_arched'), 
(1077, 'window 2×3 regular', 'window_2x3_regular'), 
(1078, 'window 2×3', 'window_2x3'), 
(1079, 'window 2×4 arched', 'window_2x4_arched'), 
(1080, 'window 2×4', 'window_2x4'), 
(1081, 'window 2×6', 'window_2x6'), 
(1082, 'window 3×1', 'window_3x1'), 
(1083, 'window 4×1', 'window_4x1'), 
(1084, 'window 4×3 arched', 'window_4x3_arched'), 
(1085, 'window 4×3', 'window_4x3'), 
(1086, 'window 4×5', 'window_4x5'), 
(1087, 'window-blinds', 'window-blinds'), 
(1088, 'window deep', 'window_deep'), 
(1089, 'window double 2×3 frame sill', 'window_double_2x3_frame_sill'), 
(1090, 'window double 3×3', 'window_double_3x3'), 
(1091, 'window double frame sill', 'window_double_frame_sill'), 
(1092, 'window flat roof skylight bubble', 'window_flat_roof_skylight_bubble'), 
(1093, 'Frosted Glass Window', 'windowFrostedGlass'), 
(1094, 'Window Shutter 1', 'window-shutter'), 
(1095, 'Window Shutter 2', 'window_shutter'), 
(1096, 'Stained-Glass Window', 'window_stain_glass'), 
(1097, 'window urban neoclassic', 'window_urban_neoclassic'), 
(1098, 'Wine Bottle', 'wine_bottle'), 
(1099, 'woman shoes', 'woman_shoes'), 
(1100, 'Wood Bank', 'wood_bank'), 
(1101, 'Alder Wood Office Table', 'wooden_office_alder_table'), 
(1102, 'Rectangular Pear Wood Office Table', 'wooden_office_pear_table_rect'), 
(1103, 'Pear Wood Office Table', 'wooden_office_pear_table'), 
(1104, 'Teak Wood Office Table', 'wooden_office_teak_table'), 
(1105, 'Wooden Office Table', 'wooden_table_office'), 
(1106, 'Wood Logs', 'wood_logs'), 
(1107, 'Wood Table', 'woodTable'), 
(1108, 'Wrought-iron Rails', 'wroughtIronRails'), 
(1109, 'Xylophone', 'xylophone'), 
(1110, 'yamaha-yzr-r6', 'yamaha-yzr-r6'), 
(1111, 'Yosemite Frame', 'YosemiteFrame');


select 'All Done' as migrations;

