#!/usr/bin/perl
# -*- cperl -*-

my $input = join "" => <>;
local $_ = $input;
while (/\<\!\-\-\#include\s+file\=\"(.*)\"\s*\-\-\>/)
{ my $file = $1;
  open INCLUDE, '<', $file or die "$file: $!";
  my $contents = join "" => <INCLUDE>;
  close INCLUDE;
  s/\<\!\-\-\#include\s+file\=\"(.*)\"\s*\-\-\>/$contents/g; }
while (/\<\!\-\-\#echo\s+var\=\"(.*)\"\s*\-\-\>/)
{ my $var = $1;
  s/\<\!\-\-\#echo\s+var\=\"\Q$var\E\"\s*\-\-\>/\${$var}/g; }

print;    