@c -*- texinfo -*- 

This is the manual for the tootsville server for CIWTA.

@node Who are CIWTA?
@section Who are CIWTA?

CIWTA, The Corporation  for Inter-World Tourism and  Adventuring, is the
non-profit corporation  responsible for  the current development  of the
Romance Ⅱ Game System, particularly,  for the flagship implementation of
it in the form of Tootsville Ⅴ.

For more information about CIWTA, visit the web site at 
@url{https://www.ciwta.org/}


@node What is Tootsville?
@section What is Tootsville?

@cindex Tootsville, what is

Tootsville is a massively-multiplayer online rôle-playing game
(MMORPG) in which players control colorful, elephant-like characters
know as Toots.

Tootsville was  the flagship product  which helped develop  the original
Romance game system into such  a powerful suite. Its commercial sponsor,
Res  Interactive,   LLC,  was  later   shut  down  for   legal  reasons.
The resurrected game  (with the permission of several  of Res's managing
members) is now the flagship for the ongoing development of Romance Ⅱ.

As such, Romance is highly and unapologetically targeted at present
towards the needs of Tootsville.

@node What is the Romance Game System?

@section What is the Romance Game System?

@cindex Romance Game System, what is

Romance is the name of the game system which runs Tootsville, and
which could, in future, be adapted to run other games as well.

The name ``Romance'' has a similar meaning to its usage in ``Romance
Languages,'' i.e. it means made of Romans, not ``romantic.'' The
original software modules of which Romance was made, and into which it
will be subdivided again for purposes of modularity in the 2.0 series,
are each named after a famous Roman.

Romance  has  a  few  technological   goals.  It  is  intended  to  be
comprehensive and flexible enough to  handle a variety of game worlds,
although it necessarily  has deep ties to Tootsville.  Romance also is
based on  a model  in which peer-to-peer  communications are  used for
real  time activities,  while  the central  servers  are reserved  for
persisting the world's state while it is quiescent.

@node Technology Stack

@section Technology Stack

Romance is built up of the following technology stack:

@itemize
@item
The  central REST  servers are  written  in Common  Lisp, compiled  to
a   native  binary,   and  run   as   a  service   under  SystemD   in
a non-privileged user account.
@item
The  client  and peer-to-peer  application  is  written in  JavaScript
(ECMAScript 6 level), and compressed using the Google Closure Compiler
into an optimized and minified form.
@end itemize

@node Affiliated Services

@section Affiliated Services

In the case of Tootsville, several affiliated services are used:

@itemize
@item
Static  web servers  running  Apache serve  up  game assets,  compiled
JavaScript, and other resources.
@item
Apache  servers operate  as load  balancers across  the back-end  game
servers
@item
The Tootsbook blog is a WordPress installation
@item
The 
@item
The central database server is a MariaDB server.
@item
Database references are cached via MemCacheD
@end itemize

@node Clusters

@section Clusters

@cindex Clusters, types of

There are four cluster types for Tootsville.

@table @code

@item local
This refers to running a full Tootsville stack on a developer's workstation

@item test.Tootsville.org
This cluster is used for testing new builds and is the most unstable,
often having a new release pushed to it every week --- sometimes,
several in one day.

@item qa.Tootsville.org
This cluster is used for longer-term testing of the code before rolling it
out to the general public.

@item Tootsville.org
This is the main production environment

@end table

@node Overview of Major Systems

@section Overview of Major Systems

There are several major systems worth understanding from a higher
level. Most of these are documented under specific functions that are
critical in those subsystems.

@subsection Methods of Connecting

@subsubsection REST Requests

@cindex REST interface
@cindex Authentication, REST

WRITEME

@subsubsection Infinity Mode communications

@cindex Infinity Mode, Overview
@cindex Authentication, Infinity Mode

WRITEME

@subsubsection The Adult Sign-in Process

WRITEME

@subsubsection The Child Sign-in Process

WRITEME

@subsection In-Game Actions


@subsubsection Moving in the Game

@cindex Movement, Overview

There have been 3 systems for character movement.

The  oldest dates  back to  Tootsville I  and was  the @code{d}  method.
This is no  longer in use. For documentation, to  the extent any exists,
refer to Tootsville IV docs. In brief, it allowed a Toot to do basically
the  same  thing  as  the  @code{wtl}  method,  only  it  compacted  the
description into a string joined with @verb{|~|} characters.

The current @emph{status  quō} method is the “d₂” method,  or ``walk the
line''  (@code{wtl})  method. The  basic  concept  is that  each  Toot's
position is determined  by a linear interpolation along  a straight line
described  by  a start  and  end  position,  a  speed of  movement,  and
a  start time.  Thus,  all  clients should  be  able  to reliably  place
a character at the same point on  the line, regardless of any lag in the
transmission. See @ref{INFINITY-WTL}- for a discussion of this method.

A more  complex system  being designed  for post-5.0  use is  the ``d₃''
method,  which  allows the  client  to  perform pathfinding  and  create
a Bezier  spline walk pattern. This  system is loosely supported  by the
server but in non-specific ways. 

@subsubsection Speech and Related Things

@cindex Speech, Overview

Speech mostly consists of public  messages. Each public message contains
a volume level, speech contents, and  musical key (for the Toot sounds).
@ref{INFINITY-SPEAK} handles the bulk of speech.

Private messaging is accomplished by  whispering to another player using
@code{@@}  messages —  i.e. the  message begins  with @code{@@}  and the
other player's name, and is processed

Operator (Builder  Toot) commands begin  with a  # and are  processed by
the server.

Client-side commands  begin with a  ~ and  are processed by  the client,
without ever sending them to the server.

WRITEME

@subsubsection Game Events System (including Store Items)

WRITEME

See @ref{INFINITY-START-EVENT} and @ref{INFINITY-END-EVENT} for an overview.

@subsubsection Land Ownership

WRITEME

@subsubsection Clothing, Tools, and Equipment

WRITEME

@subsubsection Metronome

The metronome system allows tasks to  occur on a recurring basis without
having  to keep  their own  timing threads  open all  the time.  It also
provides for one-shot events to run at a specific future time.

The  main   point  of   entry  for  scheduling   a  Metronome   task  is
DO-METRONOME.    The    metronome     thread    itself    relies    upon
RUN-METRONOME-TASKS to actually start tasks on each cycle.

Programmers are  strongly encouraged  to schedule tasks  using Metronome
throughout the game code.

@subsection World Simulation

WRITEME

@subsection Server-to-Server Streams

WRITEME

@subsection The front-end

WRITEME

@subsubsection Babylon.js

WRITEME

@subsubsection Gatekeeper

WRITEME

@subsubsection Peer-to-Peer Streams (WebRTC)

WRITEME

@subsubsection JSCL

WRITEME

@c %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

@node Back Story

@section Back Story

Once upon a time --- for all  fairy stories begin once upon a time ---
but not  too very long ago,  there were a herd  of elephants wandering
the  plains   of  Africa.  These  elephants   were  just  ``ordinary''
elephants, but of course each of them had their own personality.

...

WRITEME

...

@subsection The Magic Mist and Mist Parrots

The elephants discover the magic mist ... parrots guide them through ...

WRITEME

@subsection The Founding of Tootsville

Discover the fountain ... wish things into being ... 

WRITEME

@subsection The Classical Period

WRITEME

@subsection The Evil Mayor and Shade

WRITEME

@subsection The Destruction of Tootsville

WRITEME

@subsection The Revival

WRITEME

